name: Build Upstream Besu

on:
  push:
    branches:
      - main
      - workflow
    # enable following once we are ready to trigger release when this file is changed
    # paths:
    #  - 'version.env'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
        with:
          path: version.env
          keys-case: lower
          log-variables: true

      - name: Checkout Besu repository
        uses: actions/checkout@v4
        with:
          repository: hyperledger/besu
          ref: ${{ steps.dotenv.outputs.upstream_besu_ref }}
          path: linea-besu

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # TODO: Read project version from property file
      - name: Build Linea Besu
        working-directory: ./linea-besu
        run: ./gradlew distTar

      # TODO: Attach the build output as an artifact
